project:
  type: website

website:
  title: "Yasmine El-Kattan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact Me!

format:
  html:
    theme: journal
    css: styles.css
    toc: true